baseURL = "/"
languageCode = "ru-RU"
theme = "mk"
title = "MicroSpace"

[params]
    topmenu="blog"

[author]
    name = "MIke NIkitin"
    email = "mike@mellior.ru"
    gaid = "UA-6973180-1"

[build]
  writeStats = true


[taxonomies]
  category = 'categories'
  tag = 'tags'

[markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'colorful'
    tabWidth = 4

