baseURL = "/"
languageCode = "ru-RU"
theme = "mk"
title = "MicroSpace"

[params]
    topmenu="blog"

[author]
    name = "MIke NIkitin"
    email = "mike@mellior.ru"

[build]
  writeStats = true


[taxonomies]
  category = 'categories'
  tag = 'tags'

